import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Draggable } from "./components/draggable";
import { Droppable } from "./components/droppable";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

{/* comment this: page will load just fine, without the components below. */}
{/* keep uncommented: page will fail to load. */}

      <Draggable data={{ test: true }}>
        {({ isDragging }) => (
          <div style={{ background: "green", padding: 10, borderRadius: 7 }}>
            <span>Drag me</span>
            {isDragging && <span>Dragging</span>}
          </div>
        )}
      </Draggable>

      <Droppable onDrop={console.log}>
        <div style={{ background: "blue", width: "100%", height: 200 }}>
          <p>Drop here</p>
        </div>
      </Droppable>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
